GET http://localhost:5231/games

###
GET http://localhost:5231/games/1

###
POST http://localhost:5231/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2010-09-30"
}

# {
#     "name": "Street Fighter VI Deluxe Edition",
#     "genreId": 1,
#     "price": 63.74,
#     "releaseDate": "2023-06-02"
# }

# {
#     "name": "Minecraft",
#     "genreId": 5,
#     "price": 19.99,
#     "releaseDate": "2011-11-18"
# }

# {
#     "name": "FIFA 23",
#     "genreId": 3,
#     "price": 69.99,
#     "releaseDate": "2022-09-27"
# }

###
PUT http://localhost:5231/games/2
Content-Type: application/json

{
    "name": "Street Fighter VI Deluxe Edition 2024",
    "genreId": 1,
    "price": 63.74,
    "releaseDate": "2023-06-02"
}

###
DELETE http://localhost:5231/games/1
